AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*.rb'


Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma


Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'


Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation
