default: &default
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: sqlite3
  database: db/german-vocab-development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/german-vocab-test.sqlite3

production:
  <<: *default
  adapter: postgresql
  database: learn_german_production
  username: learn_german
  password: <%= ENV['LEARN_GERMAN_DATABASE_PASSWORD'] %>
