default: &default
  encoding: unicode
  adapter: postgresql
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: learn_german_development

test:
  <<: *default
  database: learn_german_test

production:
  <<: *default
  database: learn_german_production
  username: learn_german
  password: <%= ENV['LEARN_GERMAN_DATABASE_PASSWORD'] %>
